version: '3.1'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=teste
      - AWS_SECRET_ACCESS_KEY=teste
      - AWS_DEFAULT_REGION=sa-east-2
      - AWS_DEFAULT_OUTPUT=json
      - SERVICES=sqs
      - SQS_ENDPOINT_STRATEGY=off